System-war/src/fit5042/assignment/controllers/NormalContactController.java
package fit5042.assignment.controllers;

import java.util.ArrayList;

import javax.el.ELContext;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

@Named(value = "normalContactController")
@RequestScoped
public class NormalContactController {
	private int customerId;
	private ArrayList<fit5042.assignment.repository.entities.ContactPerson> contactPersons;
	AdminApplication app;
	
	
	public int getCustomerId() {
		return customerId;
	}


	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}


	public NormalContactController() {
		contactPersons = new ArrayList<>();
		ELContext context
    	= FacesContext.getCurrentInstance().getELContext();

		app= (AdminApplication) FacesContext.getCurrentInstance()
            .getApplication()
            .getELResolver()
            .getValue(context, null, "adminApplication");
		customerId = Integer.valueOf(FacesContext.getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("customerID"));
		app.updateContactPerson();
		
		contactPersons = getContactPersons();
	}
	
	public ArrayList<fit5042.assignment.repository.entities.ContactPerson> getContactPersons(){
			for(fit5042.assignment.repository.entities.ContactPerson p : app.getContactPersons()) {
				
						contactPersons.add(p);
					
				
				
		   }
			
		return contactPersons;
	}
	
	
	
}

System-war/src/fit5042/assignment/controllers/NormalCustomerController.java
package fit5042.assignment.controllers;

import java.util.ArrayList;

import javax.el.ELContext;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

@Named(value = "normalCustomerController")
@RequestScoped
public class NormalCustomerController {
	private int userId;
	private ArrayList<fit5042.assignment.repository.entities.Customer> customers;
	private ArrayList<fit5042.assignment.repository.entities.ContactPerson> contactPersons;
	private AdminApplication app;
	
	
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public NormalCustomerController() {
		customers = new ArrayList<>();
		contactPersons = new ArrayList<>();
		ELContext context
    	= FacesContext.getCurrentInstance().getELContext();

		app= (AdminApplication) FacesContext.getCurrentInstance()
            .getApplication()
            .getELResolver()
            .getValue(context, null, "adminApplication");
		userId = Integer.valueOf(FacesContext.getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("ID"));
		customers = getCustomers();
		contactPersons = getContactPersons();
	}
	
	public ArrayList<fit5042.assignment.repository.entities.Customer> getCustomers(){
		if(customers.size() == 0) 
		{
			for(fit5042.assignment.repository.entities.Customer c : app.getCustomers()) {
				if(c.getUser().getId() == userId) {
					customers.add(c);
				}
			}
			return customers;
		}
		return customers;
		
	}
	
	public ArrayList<fit5042.assignment.repository.entities.ContactPerson> getContactPersons(){
		if(contactPersons.size() == 0) {
			for(fit5042.assignment.repository.entities.Customer c : customers) {
				for(fit5042.assignment.repository.entities.ContactPerson p : app.getContactPersons()) {
					if(p.getCustomer().getCustomerId() == c.getCustomerId())	
					contactPersons.add(p);
					
				}
			}
			return contactPersons;
		}
		return contactPersons;
	}

	

}

System-war/src/fit5042/assignment/mbeans/SystemManagedBean.java
package fit5042.assignment.mbeans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import fit5042.assignment.repository.SystemRepository;
import fit5042.assignment.repository.entities.Address;
import fit5042.assignment.repository.entities.ContactPerson;
import fit5042.assignment.repository.entities.Customer;
import fit5042.assignment.repository.entities.Industry;
import fit5042.assignment.repository.entities.Users;




@ManagedBean(name = "systemManagedBean")
@SessionScoped
public class SystemManagedBean implements Serializable{
	@EJB
	SystemRepository systemRepository;
	

	public SystemManagedBean() {
		
	}
	
	

	public List<Users> getAllUsers() {
        try {
            List<Users> userList = systemRepository.getAllUsers();
            return userList;
        } catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
	
	
	
	public List<Customer> getAllcustomer(){
		try {
			List<Customer> customers = systemRepository.getAllCustomer();
			return customers;
		}catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
	}
	
	public List<ContactPerson> getAllContactPerson(){
		try {
			List<ContactPerson> persons = systemRepository.getAllContactPerson();
			return persons;
		}catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
	}
	
	public List<Industry> getAllIndustry(){
		try {
			List<Industry> industryList = systemRepository.getAllIndustry();
			return industryList;
		}catch (Exception ex) {
			Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
		}
		return null;
	}
	
	public void editCustomer(Customer customer) {
		try {			
			
			//customer.getIndustry().clear();
			
			int u = customer.getUser().getId();
			Users user = systemRepository.searchUsersById(u);
			customer.setUser(user);
			int i = customer.getIndustry().getId();
			Industry industry = systemRepository.searchIndustryById(i);
			customer.setIndustry(industry);
			systemRepository.editCustomer(customer);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been updated succesfully"));	
		}catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
	}
	
	public void editContact(ContactPerson person) {
		try {
			int c = person.getCustomer().getCustomerId();
			Customer customer = systemRepository.searchCustomerById(c);
			person.setCustomer(customer);
			systemRepository.editContactPerson(person);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Contact person has been updated succesfully"));	
		}catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		
		
	}
	
	public Customer searchCustomerById(int customerId) {
		try {
            return systemRepository.searchCustomerById(customerId);
        } catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
	}
	
	public List<Customer> searchCustomerByName(String customerName){
		try {
            //List<Customer> cs = systemRepository.searchCustomerByName(customerName);
			return systemRepository.searchCustomerByName(customerName);
        } catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
	}
	
	public Users searchUserById(int id){
		try {
            return systemRepository.searchUsersById(id);
        } catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
	}
	
	public void addContact(fit5042.assignment.controllers.ContactPerson localPerson) {
		ContactPerson p = convertPersonToentity(localPerson);
		try {
			
			systemRepository.addContactPerson(p);
		}catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

	}
	
	public void addCustomer(fit5042.assignment.controllers.Customer localCustomer) {
		Customer c = convertPersonToentity(localCustomer);
		try {
			
			systemRepository.addCustomer(c);
		}catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
	}
	
	public void addIndustry(fit5042.assignment.controllers.Industry localIndustry) {
		Industry i = convertIndustryToentity(localIndustry);
		try {
			systemRepository.addIndustry(i);
		}catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
	}
	
	private ContactPerson convertPersonToentity(fit5042.assignment.controllers.ContactPerson localPerson) {
		ContactPerson person = new ContactPerson();
		person.setAge(localPerson.getAge());
		
	    try {
	    	Customer c = systemRepository.searchCustomerById(localPerson.getCustomerId());
	    	person.setCustomer(c);
	    }catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		
		
		person.setEmail(localPerson.getEmail());
		person.setFirstName(localPerson.getFirstName());
		person.setLastName(localPerson.getLastName());
		person.setGender(localPerson.getGender());
		person.setPhoneNumber(localPerson.getPhoneNumber());
		person.setPersonId(localPerson.getPersonId());
		return person;
	}
	
	private Customer convertPersonToentity(fit5042.assignment.controllers.Customer localCustomer) {
		Customer customer = new Customer();
		try {
	    	Users u= systemRepository.searchUsersById(localCustomer.getUserId());
	    	customer.setUser(u);
	    }catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		try {
	    	Industry i = systemRepository.searchIndustryById(localCustomer.getIndustryId());
	    	customer.setIndustry(i);
	    }catch (Exception ex) {
            Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		Address address = new Address();
		address.setCity(localCustomer.getCity());
		address.setNation(localCustomer.getNation());
		address.setPostcode(localCustomer.getPostcode());
		address.setState(localCustomer.getState());
		customer.setAddress(address);
		customer.setCustomerId(localCustomer.getCustomerId());
		customer.setCustomerName(localCustomer.getCustomerName());
		return customer;
		
	}
	
	private Industry convertIndustryToentity(fit5042.assignment.controllers.Industry localIndustry) {
		Industry i = new Industry();
		i.setType(localIndustry.getType());
		i.setId(localIndustry.getIndustryId());
		return i;
	}
	
	public void removeContact(int personId) {
		try {
			systemRepository.removeContactPerson(personId);
		}catch (Exception ex) {
			Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
		}
		
	}
	
	public void removeCustomer(int customerId) {
		try {
			systemRepository.removeCustomer(customerId);
		}catch (Exception ex) {
			Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	public void removeIndustry(int id) {
		try {
			systemRepository.removeIndustry(id);
		}catch (Exception ex) {
			Logger.getLogger(SystemManagedBean.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	
	
	
	
	

}

System-war/WebContent/addcontact.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"> 

<h:head>
		<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title>
</h:head> 
<body> 
	<div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add ContactPerson
                </div>
            </div>
            <div>
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Create"/></h1>
                        <table class="table table-bordered ">
                            <tr>
                                <td width ="200">
                                    <h:outputLabel value="FirstName" for="firstName" />
                                </td>
                                <td>
                                    <h:inputText id="firstName" value="#{contactPerson.firstName}" title="FirstName" />
                                </td>

                            </tr>

                            <tr>
                                <td>
                                    <h:outputLabel value="LastName" for="lastName" />
                                </td>
                                <td>
                                    <h:inputText id="lastName" value="#{contactPerson.lastName}" title="LastName" />
                                </td>

                            </tr>

                            <tr>
                                <td>
                                    <h:outputLabel value="PhoneNumber" for="phoneNumber" />
                                </td>
                                <td>
                                    <h:inputText id="suburb" value="#{contactPerson.phoneNumber}" title="PhoneNumber" />
                                </td>

                            </tr>

                            <tr>
                                <td>
                                    <h:outputLabel value="Email" for="email" />
                                </td>
                                <td>
                                    <h:inputText id="email" value="#{contactPerson.email}" title="Email" />
                                </td>

                            </tr>
                            <tr>
                                <td>
                                    <h:outputLabel value="Age" for="age" />
                                </td>
                                <td>
                                    <h:inputText id="age" value="#{contactPerson.age}" title="Age" />
                                </td>

                            </tr>
                            <tr>
                                <td>
                                    <h:outputLabel value="Gender:" for="gender" />
                                </td>
                                <td>
                                    <h:inputText id="gender" value="#{contactPerson.gender}" title="Gender" />
                                </td>

                            </tr>

                            
                            <tr>
                                <td width ="100" valign="top">Customer: </td>
                                <td>
                                    <h:selectOneMenu id="customer" value="#{contactPerson.customerId}"  >
                                        <f:selectItem itemValue="#{null}" itemLabel="select" />
                                        <f:selectItems value="#{systemManagedBean.allcustomer}" var="c"  
                                                       itemLabel="#{c.customerName}" itemValue="#{c.customerId}" />
                                    </h:selectOneMenu>
                                </td>
                            </tr> 
                                 
                        </table>

                        <h:commandButton id="submit" value="Submit" action="#{addContact.addContact(contactPerson)}" class="btn btn-primary" />
                        <h:link id="close" value="Close" outcome="faces/allcontactperson.xhtml" class="btn btn-primary" />
                    </h:form>

                </f:view>
            </div>
            
        </div>
</body> 
</html>

System-war/WebContent/addindustry.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<title>Create</title>
</h:head> 
<body> 
	<div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add industry
                </div>
            </div>
            <div>
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Create"/></h1>
                        <table class="table table-bordered ">
                            <tr>
                                <td width ="200">
                                    <h:outputLabel value="Type" for="type" />
                                </td>
                                <td>
                                    <h:inputText id="type" value="#{industry.type}" title="Type" />
                                </td>

                            </tr>

                            
                                 
                        </table>

                        <h:commandButton id="submit" value="Submit" action="#{addIndustry.addIndustry(industry)}" class="btn btn-primary" />
                        <h:link id="close" value="Close" outcome="faces/allcustomer.xhtml" class="btn btn-primary" />
                    </h:form>

                </f:view>
            </div>
            
        </div>
</body> 
</html>

System-war/WebContent/contactedit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
    <title>#{titleController.pageTitle}</title>
</h:head> 
<body> 
	<div class="container">
		<div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Edit contact person
                </div>
        </div>
        <h:form id="MyForm">
        	<table class="table table-bordered ">
        		<tr>
                        <td width ="150" valign="top">Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{contactPersonController.contactPerson.personId}</h:outputLabel>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">First name: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "firstName" value="#{contactPersonController.contactPerson.firstName}" required="true"
                             
                                         requiredMessage="Please enter the first name. "></h:inputText>
                                         <br/>
                            <h:message for="firstName" class="#{!firstName.valid ? 'label label-warning' : 'none'}" />
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Last name: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "lastName" value="#{contactPersonController.contactPerson.lastName}" required="true"
                             
                                         requiredMessage="Please enter the last name. "></h:inputText>
                                         <br/>
                            <h:message for="lastName" class="#{!lastName.valid ? 'label label-warning' : 'none'}" />
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Gender: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "gender" value="#{contactPersonController.contactPerson.gender}" required="true"
                             
                                         requiredMessage="Please enter the gender. "></h:inputText>
                                         <br/>
                            <h:message for="gender" class="#{!gender.valid ? 'label label-warning' : 'none'}" />
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Age: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "age" value="#{contactPersonController.contactPerson.age}" required="true"
                             			validatorMessage="Number of rooms must be greater than 18"
                                         requiredMessage="Please enter the age. ">
                            	<f:validateLongRange minimum="18"/>
                            </h:inputText>
                            <br/>
                            <h:message for="age" class="#{!age.valid ? 'label label-warning' : 'none'}" />
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Email: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "email" value="#{contactPersonController.contactPerson.email}"  required="true"
                  
                                         requiredMessage="Please enter the email. "></h:inputText>
                                         <br/>
                            <h:message for="email" class="#{!email.valid ? 'label label-warning' : 'none'}" />
                        </td>
                </tr>
                
                <tr>
                        <td width ="100" valign="top">Phone number: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "phoneNumber" value="#{contactPersonController.contactPerson.phoneNumber}"  required="true" 
                             			 converterMessage="Please enter a number"	
                                         requiredMessage="Please enter the phone number. ">
                            	<f:convertNumber integerOnly="true"/>
                            </h:inputText>
                            <br/>
                            <h:message for="phoneNumber" class="#{!phoneNumber.valid ? 'label label-warning' : 'none'}" />
                        </td>
                </tr>
                
        		
                <tr>
                    	<td width ="100" valign="top">Customer: </td>
                    	<td>
                    	<h:selectOneMenu id="customer" value="#{contactPersonController.contactPerson.customer.customerId}" >
                        	<f:selectItem itemValue="#{null}" itemLabel="--select--" />
                        	<f:selectItems value="#{systemManagedBean.allcustomer}" var="c"  
                                       itemLabel="#{c.customerName}" itemValue="#{c.customerId}" />
                    	</h:selectOneMenu>
                    	</td>
                    </tr>
        	</table>
        	<h:commandButton id="save" value="Save" action="#{systemManagedBean.editContact(contactPersonController.contactPerson)}"  class="btn btn-primary" >
                    <f:param name="personID" value="#{contactPersonController.personId+1}"/>
            </h:commandButton>
            <h:link id="close" value="Close" outcome="faces/allcontactperson.xhtml"
						          class="btn btn-primary" />
        </h:form>
	</div>
</body> 
</html>

System-war/WebContent/customeredit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
    <title>#{titleController.pageTitle}</title>
</h:head> 
<body> 
	<div class="container">
		<div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Edit customer
                </div>
        </div>
        <h:form id="MyForm">
        	<table class="table table-bordered ">
        		<tr>
                        <td width ="150" valign="top">Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{customerController.customer.customerId}</h:outputLabel>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">customer name: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "customerName" value="#{customerController.customer.customerName}" required="true"
                             
                                         requiredMessage="Please enter the name. "></h:inputText>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">city: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "city" value="#{customerController.customer.address.city}" required="true"
                             
                                         requiredMessage="Please enter the city. "></h:inputText>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">state: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "state" value="#{customerController.customer.address.state}" required="true"
                             
                                         requiredMessage="Please enter the state. "></h:inputText>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">nation: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "nation" value="#{customerController.customer.address.nation}" required="true"
                             
                                         requiredMessage="Please enter the nation. "></h:inputText>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">postcode: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "postcode" value="#{customerController.customer.address.postcode}" binding="#{postcode}" required="true"
                             			validatorMessage="Please enter a valid postcode."
                                         requiredMessage="Please enter the city. "></h:inputText>
                        </td>
                </tr>
                <tr>
                    	<td width ="100" valign="top">Industry: </td>
                    	<td>
                    	<h:selectOneMenu id="industry" value="#{customerController.customer.industry.id}" >
                        	<f:selectItem itemValue="#{null}" itemLabel="--select--" />
                        	<f:selectItems value="#{systemManagedBean.allIndustry}" var="i"  
                                       itemLabel="#{i.type}" itemValue="#{i.id}" />
                    	</h:selectOneMenu>
                    	</td>
                    </tr>
        		
                <tr>
                    	<td width ="100" valign="top">User: </td>
                    	<td>
                    	<h:selectOneMenu id="user" value="#{customerController.customer.user.id}" >
                        	<f:selectItem itemValue="#{null}" itemLabel="--select--" />
                        	<f:selectItems value="#{systemManagedBean.allUsers}" var="u"  
                                       itemLabel="#{u.lastName}" itemValue="#{u.id}" />
                    	</h:selectOneMenu>
                    	</td>
                    </tr>
        	</table>
        	<h:commandButton id="save" value="Save" action="#{systemManagedBean.editCustomer(customerController.customer)}"  class="btn btn-primary" >
                    <f:param name="customerID" value="#{customerController.customerId+1}"/>
            </h:commandButton>
            <h:link id="close" value="Close" outcome="faces/allcustomer.xhtml"
						          class="btn btn-primary" />
        </h:form>
	</div>
</body> 
</html>

System-war/WebContent/detail.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
    <title>#{titleController.pageTitle}</title>
</h:head> 
<body> 
	<div class="container">
		<div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    Customer Details
                </div>
        </div>
        <h:form id="MyForm">
        	<table class="table table-bordered ">
        		<tr>
                        <td width ="150" valign="top">Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{customerController.customer.customerId}</h:outputLabel>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Name:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Name" >#{customerController.customer.customerName}</h:outputLabel>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Address:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Address" >#{customerController.customer.address}</h:outputLabel>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Industry:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Industry" >#{customerController.customer.industry}</h:outputLabel>
                        </td>
                </tr>
                <tr>
                        <td width ="100" valign="top">Belong to:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "User" >#{customerController.customer.user}</h:outputLabel>
                        </td>
                </tr>
        	</table>
        	<h:link id="close" value="Close" outcome="faces/allcustomer.xhtml"
 						          class="btn btn-primary" />
        </h:form>
	</div>
</body> 
</html>